PRAGMA foreign_keys = TRUE;

-- Crear la tabla de preguntas
CREATE TABLE IF NOT EXISTS PREGUNTAS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PREGUNTA TEXT
);

-- Crear la tabla de opciones
CREATE TABLE IF NOT EXISTS OPCIONES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PREGUNTA_ID INTEGER,
    OPCION TEXT,
    FOREIGN KEY (PREGUNTA_ID) REFERENCES PREGUNTAS(ID)
);

-- Crear la tabla de correcciones
CREATE TABLE IF NOT EXISTS CORRECCIONES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PREGUNTA_ID INTEGER,
    CORRECCION TEXT,
    FOREIGN KEY (PREGUNTA_ID) REFERENCES PREGUNTAS(ID)
);