INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (1,'Respuesta: c
Bibliografía: Tema 1, página 4');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (2,'Respuesta: c
Bibliografía: Tema 1, página 4');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (3,'Respuesta: b
Bibliografía: Tema 1, página 2');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (4,'Respuesta: b
Bibliografía: Tema 1, página 2');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (5,'Respuesta: b
Bibliografía: Tema 1, página 2');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (6,'Respuesta: b
Bibliografía: Tema 1, página 4');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (7,'Respuesta: c
Bibliografía: Tema 1, página 47');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (8,'Respuesta: b
Bibliografía: Tema 4, página 47');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (9,'Respuesta: c
Bibliografía: Tema 4, página 46');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (10,'Respuesta: a
Bibliografía: Tema 4, página 46');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (11,'Respuesta: a
Bibliografía: Tema 4, página 48');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (12,'Respuesta: b
Bibliografía: Tema 4, página 47');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (13,'Respuesta: a
Bibliografía: Microscopía, página 80');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (14,'Respuesta: b
Bibliografía: Microscopía, página 82');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (15,'Respuesta: c
Bibliografía: Tinciones, página 83');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (16,'Respuesta: b
Bibliografía: Tinciones, página 86');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (17,'Respuesta: d
Bibliografía: Tinciones, página 86');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (18,'Respuesta: d
Bibliografía: Tema 5.10, página 125');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (19,'Respuesta: b
Bibliografía: Tema 6, página 126');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (20,'Respuesta: b
Bibliografía: Tema 6, página 127');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (21,'Respuesta: c
Bibliografía: Tema 6, página 127');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (22,'Respuesta: d
Bibliografía: Tema 11, página 131');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (23,'Respuesta: b
Bibliografía: Tema 12, página 134');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (24,'Respuesta: b
Bibliografía: Tema 5.10, página 125');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (25,'Respuesta: b
Bibliografía: Tema 6.2, página 127');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (26,'Respuesta: a
Bibliografía: Tema 12, página 139');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (27,'Respuesta: b
Bibliografía: Tema 11, página 132');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (28,'Respuesta: a
Bibliografía: Tema 12, página 134');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (29,'Respuesta: d
Bibliografía: Tema 12, página 138');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (30,'Respuesta: b
Bibliografía: Tema 9, página 83');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (31,'Respuesta: a
Bibliografía: Tema 9, página 84');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (32,'Respuesta: a
Bibliografía: Tema 9, página 84');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (33,'Respuesta: b
Bibliografía: Tema 9, página 85');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (34,'Respuesta: a
Bibliografía: Tema 9, página 86');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (35,'Respuesta: b
Bibliografía: Inclusión, página 70');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (36,'Respuesta: c
Bibliografía: Técnicas de corte, página 73');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (37,'Respuesta: c
Bibliografía: Técnicas de corte, página 75');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (38,'Respuesta: b
Bibliografía: Microscopía, página 81');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (39,'Respuesta: b
Bibliografía: Microscopía electrónica, página 82');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (40,'Respuesta: b
Bibliografía: Tema 1, página 3');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (41,'Respuesta: b
Bibliografía: Tema 1, página 4');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (42,'Respuesta: c
Bibliografía: Tema 1, página 5');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (43,'Respuesta: c
Bibliografía: Tema 1, página 3');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (44,'Respuesta: b
Bibliografía: Tema 1, página 3');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (45,'Respuesta: c
Bibliografía: Tema 1, página 2');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (46,'Respuesta: a
Bibliografía: Página 123');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (47,'Respuesta: a
Bibliografía: Página 123');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (48,'Respuesta: c
Bibliografía: Página 124');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (49,'Respuesta: d
Bibliografía: Página 125');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (50,'Respuesta: a
Bibliografía: Página 124');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (51,'Respuesta: c
Bibliografía: Página 52');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (52,'Respuesta: b
Bibliografía: Página 53');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (53,'Respuesta: c
Bibliografía: Página 54');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (54,'Respuesta: d
Bibliografía: Página 57');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (55,'Respuesta: c
Bibliografía: Página 62');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (56,'Respuesta: c
Bibliografía: Tema 11, página 131');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (57,'Respuesta: b
Bibliografía: Tema 11, página 133');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (58,'Respuesta: b
Bibliografía: Tema 11, página 139');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (59,'Respuesta: c
Bibliografía: Tema 11, página 139');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (60,'Respuesta: c
Bibliografía: Tema 11, página 136');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (61,'Respuesta: c
Bibliografía: Tema 10, página 103');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (62,'Respuesta: a
Bibliografía: Tema 10, página 114');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (63,'Respuesta: c
Bibliografía: Tema 10, página 116');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (64,'Respuesta: b
Bibliografía: Tema 10, página 117');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (65,'Respuesta: b
Bibliografía: Tema 10, página 114');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (66,'Respuesta: c
Bibliografía: Tema 10, página 115');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (67,'Respuesta: c
Bibliografía: Tema 10, página 116');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (68,'Respuesta: b
Bibliografía: Tema 10, página 117');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (69,'Respuesta: b
Bibliografía: Tema 10, página 118');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (70,'Respuesta: b
Bibliografía: Tema 9, página 83');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (71,'Respuesta: a
Bibliografía: Tema 9, página 84');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (72,'Respuesta: b
Bibliografía: Tema 9, página 84');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (73,'Respuesta: a
Bibliografía: Tema 9, página 85');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (74,'Respuesta: c
Bibliografía: Tema 9, página 85');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (75,'Respuesta: a
Bibliografía: Tema 9, página 83');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (76,'Respuesta: c
Bibliografía: Tema 9, página 85');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (77,'Respuesta: c
Bibliografía: Tema 9, página 80');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (78,'Respuesta: a
Bibliografía: Tema 9, página 84');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (79,'Respuesta: b
Bibliografía: Tema 9, página 84');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (80,'Respuesta: b
Bibliografía: Tema 8, página 70');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (81,'Respuesta: a
Bibliografía: Tema 8, página 70');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (82,'Respuesta: b
Bibliografía: Tema 8, página 70');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (83,'Respuesta: c
Bibliografía: Tema 8, página 70');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (84,'Respuesta: c
Bibliografía: Tema 7, página 65');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (85,'Respuesta: b
Bibliografía: Tema 7, página 66');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (86,'Respuesta: d
Bibliografía: Tema 7, página 66');
INSERT INTO CORRECCIONES (PREGUNTA_ID,CORRECCION) VALUES (87,'Respuesta: b
Bibliografía: Tema 7, página 68');